version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: AzureDiamond
      MONGO_INITDB_ROOT_PASSWORD: hunter2
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
